services:
  mongo:
    image: mongo:6.0
    container_name: pc_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: pc_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"

  api:
    build: .
    container_name: pc_api
    depends_on:
      - mongo
      - elasticsearch
    environment:
      - MONGO_URI=mongodb://root:password@mongo:27017/catalog?authSource=admin
      - ELASTIC_URL=http://elasticsearch:9200
      - PORT=3000
    ports:
      - "3000:3000"

volumes:
  mongo_data:
